name: agrimate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logo_withname.png
     - assets/images/logo_withoutname.png
     - assets/images/onboarding1.png
     - assets/images/onboarding2.png
     - assets/images/onboarding3.png
     - assets/icons/paddy.svg
     - assets/icons/checked.svg
     - assets/icons/handshake.svg
     - assets/icons/tea.svg
     - assets/icons/store.svg
